package domain

import "errors"

var (
	ErrInvalidRunMode                = errors.New("run_mode: invalid value")
	ErrInvalidBatchMode              = errors.New("batch_mode: invalid value")
	ErrBatchSizeNotPositive          = errors.New("batch_size: must be greater than 0")
	ErrVectorEmpty                   = errors.New("vector must not be empty")
	ErrVectorComponentNaN            = errors.New("vector component must not be NaN")
	ErrVectorComponentInf            = errors.New("vector component must not be infinite")
	ErrVectorNormZero                = errors.New("vector norm must not be zero")
	ErrIDEmpty                       = errors.New("id must not be empty")
	ErrNameEmpty                     = errors.New("name must not be empty")
	ErrCentroidEmpty                 = errors.New("centroid must not be empty")
	ErrNoteIDsEmpty                  = errors.New("note_ids must not be empty")
	ErrNoteIDEmpty                   = errors.New("note_ids entry must not be empty")
	ErrSlugEmpty                     = errors.New("slug must not be empty")
	ErrSlugPathSeparators            = errors.New("slug must not contain path separators")
	ErrTimeMustNotBeZero             = errors.New("must not be zero")
	ErrTimeMustBeUTC                 = errors.New("must be UTC")
	ErrNoteIDMismatch                = errors.New("id does not match source chat/message")
	ErrTitleEmpty                    = errors.New("title must not be empty")
	ErrBodyEmpty                     = errors.New("body must not be empty")
	ErrBodyCarriageReturn            = errors.New("body must not contain carriage returns")
	ErrBodyTrailingNewline           = errors.New("body must not end with a newline")
	ErrEmbeddingIDEmpty              = errors.New("embedding id must not be empty")
	ErrClusterIDEmpty                = errors.New("cluster id must not be empty")
	ErrUpdatedBeforeCreated          = errors.New("updated_at must not be before created_at")
	ErrDuplicateOfEqualsID           = errors.New("duplicate_of must not equal id")
	ErrEmbeddingEmpty                = errors.New("embedding must not be empty")
	ErrDuplicateNoteIDInCluster      = errors.New("note_ids: duplicate note id")
	ErrInvalidInteger                = errors.New("invalid integer")
	ErrNotesNegative                 = errors.New("notes: must not be negative")
	ErrCanonicalNotesNegative        = errors.New("canonical_notes: must not be negative")
	ErrDuplicateNotesNegative        = errors.New("duplicate_notes: must not be negative")
	ErrClustersNegative              = errors.New("clusters: must not be negative")
	ErrNotesCountMismatch            = errors.New("notes: expected canonical_notes + duplicate_notes to equal notes")
	ErrFinishedBeforeStarted         = errors.New("finished_at_utc must not be before started_at_utc")
	ErrRunIDEmpty                    = errors.New("run_id must not be empty")
	ErrUnsupportedSchemaVersion      = errors.New("schema_version: unsupported value")
	ErrModelIDEmpty                  = errors.New("model_id must not be empty")
	ErrModelHashEmpty                = errors.New("model_hash must not be empty")
	ErrModelProfileEmpty             = errors.New("model_profile must not be empty")
	ErrUnsupportedNormalizationRule  = errors.New("normalization_rule: unsupported value")
	ErrVectorDimensionInvalid        = errors.New("vector_dimension: must be greater than 0")
	ErrDuplicateNoteID               = errors.New("duplicate note id")
	ErrDuplicateClusterID            = errors.New("duplicate cluster id")
	ErrDuplicateClusterSlug          = errors.New("duplicate cluster slug")
	ErrClusterIDNotFound             = errors.New("cluster_id does not reference an existing cluster")
	ErrDuplicateOfNotFound           = errors.New("duplicate_of does not reference an existing canonical note")
	ErrDuplicateOfClusterMismatch    = errors.New("duplicate_of must belong to the same cluster")
	ErrClusterNoteIDNotFound         = errors.New("note id does not reference an existing note")
	ErrClusterNoteClusterMismatch    = errors.New("note id belongs to a different cluster")
	ErrClusterMissingNoteID          = errors.New("cluster is missing note id")
	ErrEmbeddingDimensionMismatch    = errors.New("embedding dimension does not match vector_dimension")
	ErrCentroidDimensionMismatch     = errors.New("centroid dimension does not match vector_dimension")
	ErrSimilarityOutOfRange          = errors.New("must be within (0, 1]")
	ErrSourceChatEmpty               = errors.New("source chat must not be empty")
	ErrSourceMessageIDNotPositive    = errors.New("source message ID must be positive")
	ErrEditedAtBeforeDate            = errors.New("edited_at_utc must be greater than or equal to date_utc")
	ErrReplyToSourceMsgIDNotPositive = errors.New("reply_to_source_msg_id must be positive")
)
